services:
  api:
    container_name: agro-predict-api-dev
    env_file:
      - .env.dev
    environment:
      - DEBUG=true
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - API_PORT=8150
    ports:
      - "8150:8000"
