services:
  db:
    environment:
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro123
      POSTGRES_DB: agropredict
    ports:
      - "5432:5432"

  api:
    container_name: agro-predict-api-dev
    env_file:
      - .env.dev
    environment:
      - DATABASE_URL=postgresql+psycopg2://agro:agro123@db:5432/agropredict
    ports:
      - "8000:8000"

volumes:
  postgres_data:
