services:
  api:
    container_name: agro-predict-api-prod
    env_file:
      - .env.prod
    environment:
      - DEBUG=false
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8150:8000"
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
