"""add badge to menus

Revision ID: 4e7e2034c310
Revises: bc88a62fff67
Create Date: 2026-09-10 02:22:12.386054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7e2034c310'
down_revision: Union[str, None] = 'bc88a62fff67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('badge', sa.String(length=50), nullable=True), schema='security')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'badge', schema='security')
    # ### end Alembic commands ###
