"""remove unique constraint from roles name

Revision ID: 5ca8d3ce812a
Revises: 4e7e2034c310
Create Date: 2026-09-15 01:08:14.855575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca8d3ce812a'
down_revision: Union[str, None] = '4e7e2034c310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_name_key', 'roles', schema='security', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], schema='security')
    # ### end Alembic commands ###
